### ISSUE TITLE
The `User-Agent` value in `app/invitation.py` should be set to `LeagueOfLegendsClient` instead of `Mozilla/...`

### ISSUE THREAD

**Issue by rwech** [ThanatosDi/LoLTW_10Year_88Event#1]

**Comment by ThanatosDi** [comment]
I used wireshark to catch and decrypt requests, I also found user-agent is `Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) LeagueOfLegendsClient/11.15.388.2387 (CEF 74) Safari/537.36`

![image](https://user-images.githubusercontent.com/12424898/128134961-9390e74b-b275-4e65-9cbe-72ac5392d584.png)

But I haven't tried it works

**Comment by rwech** [comment]
I used the following `User-Agent` value but received the `Bad Request` and it just worked after modifying `User-Agent` to `LeagueOfLegendsClient`.

```py
    # in app/invitation.py, line 19
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36',
```

So I think that maybe the critical point of the `User-Agent` is `LeagueOfLegendsClient`.
